<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TareasProfesor.aspx.cs" Inherits="HADS_IBER_EVAR.WebForm4" %>

<!DOCTYPE html>
<%@ Register TagPrefix="ajaxToolkit" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit" %>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        <div>
            <asp:Label ID="Label1" runat="server" Text="PROFESOR"></asp:Label>
            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/CerrarSesion.aspx">Cerrar sesión</asp:HyperLink>
        </div>
        <p>
            <asp:Label ID="Label2" runat="server" Text="GESTIÓN DE TAREAS GENÉRICAS"></asp:Label>
            
        </p>
            <asp:ScriptManager ID="ScriptManager1" runat="server" EnableScriptGlobalization="True">
                </asp:ScriptManager>
                    <asp:Label ID="Label3" runat="server" Text=" Seleccionar asignatura"></asp:Label>
                    <br />
                    <asp:DropDownList ID="dlAsignaturas" runat="server" AutoPostBack="True" DataSourceID="sqlTareasProf" DataTextField="codigo" OnSelectedIndexChanged="dlAsignaturas_SelectedIndexChanged1">
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="sqlTareasProf" runat="server" ConnectionString="<%$ ConnectionStrings:HADS21-19ConnectionString %>" SelectCommand="SELECT Asignaturas.codigo FROM Usuarios CROSS JOIN Asignaturas WHERE (Usuarios.email = @email)">
                        <SelectParameters>
                            <asp:SessionParameter DbType="String" Name="email" SessionField="email" />
                        </SelectParameters>
                    </asp:SqlDataSource>
            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                <ContentTemplate>
                    <br />
                    <asp:GridView ID="gvTareasProf" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderStyle="Outset" DataKeyNames="Codigo" DataSourceID="sqlTareasProfTabla" OnSelectedIndexChanged="gvTareasProf_SelectedIndexChanged" ShowHeaderWhenEmpty="True">
                        <Columns>
                            <asp:BoundField DataField="Codigo" HeaderText="Codigo" ReadOnly="True" SortExpression="Codigo" />
                            <asp:BoundField DataField="Descripcion" HeaderText="Descripcion" SortExpression="Descripcion" />
                            <asp:BoundField DataField="CodAsig" HeaderText="CodAsig" SortExpression="CodAsig" />
                            <asp:BoundField DataField="HEstimadas" HeaderText="HEstimadas" SortExpression="HEstimadas" />
                            <asp:CheckBoxField DataField="Explotacion" HeaderText="Explotacion" SortExpression="Explotacion" />
                            <asp:BoundField DataField="TipoTarea" HeaderText="TipoTarea" SortExpression="TipoTarea" />
                        </Columns>
                    </asp:GridView>
                </ContentTemplate>
            </asp:UpdatePanel>
            <p>
                    <asp:SqlDataSource ID="sqlTareasProfTabla" runat="server" ConnectionString="<%$ ConnectionStrings:HADS21-19ConnectionString %>" DeleteCommand="DELETE FROM [TareasGenericas] WHERE [Codigo] = @Codigo" InsertCommand="INSERT INTO [TareasGenericas] ([Codigo], [Descripcion], [CodAsig], [HEstimadas], [Explotacion], [TipoTarea]) VALUES (@Codigo, @Descripcion, @CodAsig, @HEstimadas, @Explotacion, @TipoTarea)" SelectCommand="SELECT * FROM [TareasGenericas] WHERE ([CodAsig] = @CodAsig)" UpdateCommand="UPDATE [TareasGenericas] SET [Descripcion] = @Descripcion, [CodAsig] = @CodAsig, [HEstimadas] = @HEstimadas, [Explotacion] = @Explotacion, [TipoTarea] = @TipoTarea WHERE [Codigo] = @Codigo">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="dlAsignaturas" DbType="String" DefaultValue="" Name="codasig" PropertyName="SelectedValue" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                <asp:Button ID="btnInsertar" runat="server" Text="Insertar nueva tarea" OnClick="btnInsertar_Click" style="height: 26px" />
        </p>
        </div>
    </form>
</body>
</html>
